version: 2

models:
  - name: stg_global_superstore
    description: Cleaned staging model for Global Superstore data

    columns:
      - name: ORDER_ID
        tests:
          - not_null

      - name: SALES
        tests:
          - not_null

      - name: CATEGORY
        tests:
          - not_null